Bag of Words

In [6]:
import numpy as np
import pandas as pd

In [24]:
df = pd.DataFrame({
    'text': [
        'I love programming! 😊',
        'Python is awesome Data is Awesome Python awesome! 🚀',
        'Data Science is the future! 📊',
        'Statistics is boring! 🎲',
        'Machine Learning is fascinating! 🤖',
        'Mathemtics is hard! 🧮'
    ], 'label': [1, 1, 1, 0, 1, 0]
})

df

,text,label
0,I love programming! 😊,1
1,Python is awesome Data is Awesome Python aweso...,1
2,Data Science is the future! 📊,1
3,Statistics is boring! 🎲,0
4,Machine Learning is fascinating! 🤖,1
5,Mathemtics is hard! 🧮,0


In [25]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()


In [26]:
X = vectorizer.fit_transform(df['text'])
print(vectorizer.vocabulary_)
print(X.toarray())

{'love': 8, 'programming': 11, 'python': 12, 'is': 6, 'awesome': 0, 'data': 2, 'science': 13, 'the': 15, 'future': 4, 'statistics': 14, 'boring': 1, 'machine': 9, 'learning': 7, 'fascinating': 3, 'mathemtics': 10, 'hard': 5}
[[0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0]
 [3 0 1 0 0 0 2 0 0 0 0 0 2 0 0 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 1]
 [0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0]]


In [29]:
vectorizer.transform(["I love Python Python is love! 😊"]).toarray()

array([[0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0]], dtype=int64)

N-grams: the N defines how many words to consider in a token

In [31]:
vectorizer2 = CountVectorizer(ngram_range=(2,2))

In [32]:
X2 = vectorizer2.fit_transform(df['text'])
print(vectorizer2.vocabulary_)

{'love programming': 10, 'python is': 14, 'is awesome': 4, 'awesome data': 0, 'data is': 2, 'awesome python': 1, 'python awesome': 13, 'data science': 3, 'science is': 15, 'is the': 8, 'the future': 17, 'statistics is': 16, 'is boring': 5, 'machine learning': 11, 'learning is': 9, 'is fascinating': 6, 'mathemtics is': 12, 'is hard': 7}


In [33]:
print(X2.toarray())

[[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [1 1 1 0 2 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0]]


TF-IDF

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
TfidfVectorizer = TfidfVectorizer()

In [36]:
X3 = TfidfVectorizer.fit_transform(df['text'])
print(TfidfVectorizer.vocabulary_)
print(X3.toarray())


{'love': 8, 'programming': 11, 'python': 12, 'is': 6, 'awesome': 0, 'data': 2, 'science': 13, 'the': 15, 'future': 4, 'statistics': 14, 'boring': 1, 'machine': 9, 'learning': 7, 'fascinating': 3, 'mathemtics': 10, 'hard': 5}
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.70710678 0.         0.         0.70710678
  0.         0.         0.         0.        ]
 [0.78186696 0.         0.21371403 0.         0.         0.
  0.26704756 0.         0.         0.         0.         0.
  0.52124464 0.         0.         0.        ]
 [0.         0.         0.41338476 0.         0.50411896 0.
  0.25827362 0.         0.         0.         0.         0.
  0.         0.50411896 0.         0.50411896]
 [0.         0.66482563 0.         0.         0.         0.
  0.34060794 0.         0.         0.         0.         0.
  0.         0.         0.66482563 0.        ]
 [0.         0.         0.         0.55363834 0.         0.
  0.28364372 0.55363834 0.         0.55

Word2Vec